version: "3"
services:
  mysql:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: gitbase
  mysq2l:
    image: mysql:8.0.27
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin22
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: gitbase