version: "3"
services:
  bootstrap:
    build: ./
    volumes:
      - ./pluginb/target/pluginb-1.0-SNAPSHOT.jar:/opt/plugins/pluginb-1.0-SNAPSHOT.jar
      - ./plugina/target/plugina-1.0-SNAPSHOT.jar:/opt/plugins/plugina-1.0-SNAPSHOT.jar
      - ./pluginc/target/pluginc-1.0-SNAPSHOT.jar:/opt/plugins/pluginc-1.0-SNAPSHOT.jar
    ports:
      - "8080:8080"
      - "8849:8849"
  mysql:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: gitbase
  mysq2l:
    image: mysql:8.0.27
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin22
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: gitbase